name: Autoping

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  human-rights-day:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: ping
        run: curl -s -o /dev/null -w "PING | %{http_code} | $(date '+%Y-%m-%d %H:%M:%S') | %{time_total}s | %{size_download}B | %{remote_ip} | %{url_effective} \n" https://denlidskychprav.pages.dev/ >> monitor.log

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "monitoring(autoping): store latest curl response results of 'human-right-day' website"
          file_pattern: "monitor.log"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"